INSERT INTO Blog (id, title, description, valid) VALUES
(1, 'Die Zukunft des Klimaschutzes', 'Aktuelle Herausforderungen und Lösungsansätze.', true),
(2, 'Reisebericht: Neuseeland entdecken', 'Eine atemberaubende Reise durch Neuseeland.', true),
(3, 'Künstliche Intelligenz in der Medizin', 'Revolutionäre Diagnose- und Behandlungsmethoden.', true),
(4, 'Nachhaltigkeit im Alltag', 'Praktische Tipps für umweltbewusstes Leben.', true),
(5, 'Zeitmanagementstrategien', 'Effektiver arbeiten und ausgewogen leben.', true),
(6, 'Neue Trends in der Mode', 'Aktuelle Entwicklungen und Styling-Tipps.', true),
(7, 'Gesunde Ernährungstipps', 'Leckere Rezepte und Ernährungsberatung.', true),
(8, 'Die Macht der Positivität', 'Wie positive Einstellungen das Leben verbessern können.', true),
(9, 'Fitness für Anfänger', 'Einfache Übungen für den Einstieg ins Training.', true),
(10, 'Geld sparen im Haushalt', 'Praktische Spartipps für den Alltag.', true),
(11, 'Die Kunst des Kochens', 'Kreative Rezeptideen und Kochtechniken.', true),
(12, 'Motivation im Alltag', 'Tipps, um motiviert zu bleiben.', true),
(13, 'DIY-Projekte für Zuhause', 'Kreative Ideen für Heimwerkerprojekte.', true),
(14, 'Karriereplanungstipps', 'Strategien für beruflichen Erfolg.', true),
(15, 'Entspannungstechniken', 'Stressabbau und innere Ruhe finden.', true),
(16, 'Digitale Fotografie-Tipps', 'Grundlagen der Fotografie und Bearbeitung.', true),
(17, 'Gesundheit am Arbeitsplatz', 'Ergonomie und Wohlbefinden im Büro.', true),
(18, 'Familienausflugsideen', 'Ausflugstipps für die ganze Familie.', true),
(19, 'Effizientes Lernen', 'Methoden für erfolgreiches Studieren.', true),
(20, 'Schlafhygiene verbessern', 'Tipps für besseren Schlaf und Erholung.', true),
(21, 'Karrierechancen im Technologiesektor', 'Jobsuche und Weiterbildung.', true),
(22, 'Kleine Veränderungen, große Wirkung', 'Alltagsgewohnheiten verbessern.', true),
(23, 'Die Kunst des Schreibens', 'Kreative Schreibtechniken und Inspiration.', true),
(24, 'Outdoor-Aktivitäten für Abenteurer', 'Abenteuerliche Freizeitgestaltungsideen.', true),
(25, 'Minimalistisches Wohnen', 'Weniger besitzen, mehr genießen.', true),
(26, 'Konfliktlösungsstrategien', 'Kommunikationstechniken für Konfliktsituationen.', true),
(27, 'Neue Trends in der Technologie', 'Innovative Technologien und Gadgets.', true),
(28, 'Gesunde Snackideen', 'Leckere und gesunde Snackrezepte.', true),
(29, 'Entdecke die Welt der Kunst', 'Kunstgeschichte und moderne Kunst.', true),
(30, 'Nachhaltige Mode', 'Fair Fashion und ökologische Kleidung.', true),
(31, 'Teamwork verbessern', 'Strategien für effektive Teamarbeit.', true),
(32, 'Digitales Marketing für Anfänger', 'Grundlagen des Online-Marketings.', true),
(33, 'Die Kraft der Meditation', 'Stressbewältigung und Achtsamkeit.', true),
(34, 'DIY-Geschenkideen', 'Persönliche Geschenke selber machen.', true),
(35, 'Gesunde Gewohnheiten für Kinder', 'Gesunde Ernährung und Bewegung.', true),
(36, 'Finanzielle Unabhängigkeit erreichen', 'Sparen und investieren.', true),
(37, 'Kreative Schreibideen', 'Inspiration für kreative Texte.', true),
(38, 'Einfache Wohnkultur-Ideen', 'Raumgestaltungstipps für Zuhause.', true),
(39, 'Grundlagen der Persönlichkeitsentwicklung', 'Selbstreflexion und Wachstum.', true),
(40, 'Digitale Sicherheitstipps', 'Sicherheitspraktiken im Internet.', true),
(41, 'Gesunde Smoothie-Rezepte', 'Fruchtige und vitaminreiche Smoothies.', true),
(42, 'Effektive Kommunikation am Arbeitsplatz', 'Konstruktives Feedback und Teamkommunikation.', true),
(43, 'DIY-Gartenprojekte', 'Gartenarbeit und Landschaftsgestaltung.', true),
(44, 'Die Kunst des Zuhörens', 'Aktives Zuhören und Empathie.', true),
(45, 'Einfache Yoga-Übungen', 'Entspannung und Flexibilität durch Yoga.', true),
(46, 'Kreative Bastelideen für Kinder', 'Basteln und Spielen für Kinder.', true),
(47, 'Berufliche Neuorientierung', 'Tipps für einen erfolgreichen Berufswechsel.', true),
(48, 'Gesunde Lebensmittel einkaufen', 'Tipps für eine ausgewogene Ernährung.', true),
(49, 'Effektive Lerntechniken für Prüfungen', 'Vorbereitung und Stressbewältigung.', true),
(50, 'Die Macht der Gewohnheiten', 'Gewohnheiten ändern und Ziele erreichen.', true),
(51, 'Digitale Nomadenlebensstil', 'Arbeiten und Reisen um die Welt.', false),
(52, 'Umweltfreundliche Haushaltsprodukte', 'Nachhaltige Alternativen für den Haushalt.', false),
(53, 'Gesunde Lebensmittelzubereitung', 'Gesund kochen und genießen.', false),
(54, 'Effektive Zeitmanagementtechniken', 'Prioritäten setzen und organisieren.', false),
(55, 'Die Kunst des Kochens', 'Kreative Rezepte und Küchentechniken.', false),
(56, 'Outdoor-Abenteuer für Naturliebhaber', 'Wandern, Camping und mehr.', false),
(57, 'Selbstmotivation steigern', 'Inspiration für persönliches Wachstum.', false),
(58, 'Kreative Fotografieprojekte', 'Experimentieren und gestalten.', false),
(59, 'Effektive Teamführung', 'Motivation und Führungskompetenz.', false),
(60, 'Kleine Veränderungen für ein gesünderes Leben', 'Gesundheitsbewusstsein im Alltag.', false),
(61, 'Einfache Haushaltstipps', 'Praktische Lösungen für den Haushalt.', false),
(62, 'Kreatives Schreiben für Anfänger', 'Grundlagen und Übungen.', false);